apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-preview
  namespace: preview-hugo-cv-pr-{{ .Values.pr }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-preview
  template:
    metadata:
      labels:
        app: cv-preview
        pr: {{ .Values.pr | quote }}
        sha: {{ .Values.sha | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cv
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
